#### ==================================================================== ####
#### Simulation parameters for Die-to-Wafer (W2W) hybrid bonding simulation.
#### ==================================================================== ####
d2w_simulation:
  # === General Settings ===
  MODE: "D2W_Hybrid_Bonding_Simulation" # Name of the simulation
  DEBUG: false                          # Enable debug mode
  OUTPUT_DIR: "output/"
  INPUT_DIR: "input/"          # Output directory for simulation results
  DESIGN: "HBM_footprint_A_dummy_row_2"                      # Design name  
  # === Die Settings ===
  NUM_DIES: 1000                            # Number of Dies used in simulation
  PITCH_r_um: 55                            # Row pad pitch (µm) (In checkerboard layout, this is sqrt(2)/2 times of the real pitch)
  PITCH_c_um: 35                            # Column pad pitch (µm)  (In checkerboard layout, this is sqrt(2)/2 times of the real pitch)
  DIE_W_um: 10990                          # Die width (µm)
  DIE_L_um: 9185                          # Die length (µm)
  PAD_ARR_ROW: 165
  PAD_ARR_COL: 312
  PAD_BOT_R_um: 9                      # Bottom Cu pad radius (um)
  PAD_TOP_R_um: 9                      # Top Cu pad radius (um)
  VOID_SHAPE: "circle"                  # Void shape: "circle" or "square"
  dice_width: 100                      # Width of one die (µm)
  pad_yield_flag: True
  pad_yield_map_sub_factor: 1          # Subsampling factor for pad yield map (1: no subsampling, 10: rows/10 and cols/10)
  PAD_ARRANGE_PATTERN: "checkerboard"

  # === Die Warpage Peeling Stress Mdodel ===
  # === Bottom Wafer Settings ===
  B_Chip_Cu_V: 0.40                     # Efficient chip layer Cu volume density
  B_Chip_Sio2_V: 0.60                   # Efficient chip layer Sio2 volume density
  B_Chip_Si_V: 0.00                     # Efficient chip layer Si volume density
  B_Chip_T: 3.2e-6                      # Efficient chip layer thickness (m)
  B_Sub_Cu_V: 0.10                      # Efficient substrate layer Cu volume density
  B_Sub_Sio2_V: 0.00                    # Efficient substrate layer Sio2 volume density
  B_Sub_Si_V: 0.90                      # Efficient substrate layer si volume density
  B_Sub_T: 775e-6                       # Efficient substrate layer thickness (m)
  S_INIT_A_M: 100e-9                     # Pre-anneal warpages (m)
  # === Top Wafer Settings ===
  T_Chip_Cu_V: 0.30                     # Efficient chip layer Cu volume density
  T_Chip_Sio2_V: 0.70                   # Efficient chip layer Sio2 volume density
  T_Chip_Si_V: 0.00                     # Efficient chip layer Si volume density
  T_Chip_T: 3.2e-6                      # Efficient chip layer thickness (m)
  T_Sub_Cu_V: 0.10                      # Efficient substrate layer Cu volume density
  T_Sub_Sio2_V: 0.00                    # Efficient substrate layer Sio2 volume density
  T_Sub_Si_V: 0.90                      # Efficient substrate layer si volume density
  T_Sub_T: 775e-6                       # Efficient substrate layer thickness (m)
  S_INIT_B_M: 0.0e-6                    # Pre-anneal warpages (m)

 

  CONTACT_AREA_CONSTRAINT: 0.75         # Minimum allowed contact area ratio
  CRITICAL_DIST_CONSTRAINT: 0.75        # Minimum distance constraint for critical pads

  # === Misalignment Parameters ===
  RANDOM_MISALIGNMENT_MEAN_um: 0        # Random misalignment mean (µm)
  RANDOM_MISALIGNMENT_STD_um: 2e-2         # Random misalignment standard deviation (µm)
  SYSTEM_TRANSLATION_X_MEAN_um: 0       # Systematic X translation mean (µm)
  SYSTEM_TRANSLATION_X_STD_um: 2e-2        # Systematic X translation std (µm)
  SYSTEM_TRANSLATION_Y_MEAN_um: 0e-3       # Systematic Y translation mean (µm)
  SYSTEM_TRANSLATION_Y_STD_um: 2e-2        # Systematic Y translation std (µm)
  SYSTEM_ROTATION_MEAN_rad: 2e-6            # Systematic rotation mean (rad)
  SYSTEM_ROTATION_STD_rad: 5e-7             # Systematic rotation std (rad)

  # === Bowing and Magnification ===
  BOW_DIFFERENCE_MEAN_um: 0.5               # Bow difference mean (µm)
  BOW_DIFFERENCE_STD_um: 0.1                 # Bow difference std (µm)
  k_mag: 0.1                           # Magnification slope coefficient
  M_0: 0                                # Magnification offset

  # === Defect Parameters ===
  first_contact: 'center'            # First contact location: 'center' or 'edge' or 'corner (left-top)'
  D0: 2e-9                              # Particle density (1/µm²)
  z: 3                                  # Particle thickness distribution exponent
  t_0: 0.1                                # Minimum particle thickness (µm)
  k_r: 1.8e-4
  k_r0: 230
  k_L: 6.2e-2
  k_n: 9e-5
  k_S: 2.7

  # === Cu Dishing Parameters ===
  TOP_DISH_MEAN_nm: -2.0                  # Top pad dish mean (nm)
  TOP_DISH_STD_nm: 0.3                     # Top pad dish std (nm)
  BOT_DISH_MEAN_nm: -2.0                  # Bottom pad dish mean (nm)
  BOT_DISH_STD_nm: 0.3                     # Bottom pad dish std (nm)
  k_et: 0.053                           # Top Cu expansion coefficient (nm/K)
  k_eb: 0.053                           # Bottom Cu expansion coefficient (nm/K)
  T_R: 25                               # Room temperature (°C)
  T_anl: 300                            # Annealing temperature (°C)
  CU_E_GPA: 91.8                        # Cu Young’s modulus (GPa)
  CU_NU: 0.34                           # Cu Poisson’s ratio 
  CU_ALPHA_PPM: 17.6                    # Cu coefficient of thermal expansion (CTE) (ppm/°C)
  OX_E_GPA: 73.0                        # Sio2 Young’s modulus (GPa)
  OX_NU: 0.17                           # Sio2 Poisson’s ratio
  OX_ALPHA_PPM: 0.5                     # Sio2 coefficient of thermal expansion (CTE) (ppm/°C)
  SI_E_GPA: 131.0                        # Si Young’s modulus (GPa)
  SI_NU: 0.28                           # Si Poisson’s ratio
  SI_ALPHA_PPM: 2.6                     # Si coefficient of thermal expansion (CTE) (ppm/°C)

  # === Cu & Sio2 peeling stress model Parameters ===
  # === heat up and dwell stage ===
  # σ_m = σ_e + R_P * σ_p + R_C * σ_c
  # σ_e = {σ_t, SIGMA_Y_MPA}_min 
  # σ_p = {0, σ_t-SIGMA_Y_MPA}_max
  # σ_d = CREEP_FACTOR * σ_m
  SIGMA_Y_MPA: 321.0                    # Elastic yield point (MPa)
  R_P: 60.0                             # Weight of plastic part in the normal-approach driver
  R_C: 20.0                             # Weight of creep-equivalent part in the normal-approach driver
  CREEP_FACTOR: 0.01                    # Weight of creep-equivalent part for dwell stage
  
  # t_cu(T) = TCU_BASE_UM * exp(TCU_K_PER_C * (T - T_R))
  TCU_BASE_UM: 0.036                    # Base thickness for heat-stage Cu participation thickness (µm)
  TCU_K_PER_C: 0.0031                   # Exponential temperature rate (1/°C)
 
  # ϕ = PHI_CU0 + (1 - PHI_CU0)*((δ-2*Dishing)/2*Dishing)^ETA_GROWTH
  PHI_CU0: 0.000001                     # Baseline Cu–Cu contact fraction once the threshold is exceeded
  ETA_GROWTH: 0.122019                  # Power exponent in the (uncapped) contact growth law
  
  # k_n = M_cu/T_INT_NM
  T_INT_NM: 13000.0                     # Interface normal compliance thickness (nm)

  # === heat up and dwell stage ===
  # σy_cool = {SIGMA_Y_MPA, (1-COOL_BAUSINGER_REDUCTION) * SIGMA_Y_MPA + COOL_A_HARD_MPA * (1 - exp(-COOL_K_HARD_PER_MPA * {0,σ_p_heat}_max)) }_min
  COOL_BAUSINGER_REDUCTION: 0.70        # Cool-down effective yield reduction factor
  COOL_A_HARD_MPA: 80.0                 # Isotropic hardening Amplitude (MPa)
  COOL_K_HARD_PER_MPA: 0.032380         # Isotropic hardening rate (1/MPa)

  # kn_cool = k_n * KN_COOL_GAIN * (1- VISC_LAMBDA*(Acu/Acell)^VISC_EXP)
  KN_COOL_GAIN: 3.0                     # Gain of interface normal stiffness at cool-down
  VISC_LAMBDA: 0.836626                 # Coefficient of viscous attenuation applied to the Cu–Cu peel stress during cool-down
  VISC_EXP: 0.5                         # Sensitivity of stress reduction to fill fraction
  
  # ke_cool = TCU_CONST_UM_COOL* (1 + KDISH_TCU_GAIN_PER_NM * Dishing)
  TCU_CONST_UM_COOL: 0.122074           # Constant Cu participation thickness during the cool-down stage (µm)
  KDISH_TCU_GAIN_PER_NM: 0.010466       # Coefficient for the linear dishing gain applied to Cu participation thickness (1/nm)

  # === Roughness Parameters ===
  Asperity_R_m: 2e-6                      # Asperity curvature radius (m)
  Roughness_sigma_m: 0.5e-9                 # Surface roughness std (m)
  eta_s: 40e12                          # Asperity density (1/m²)
  Roughness_constant: 0.07
  Adhesion_energy: 1.2                  # Adhesion energy (J/m²)
  Dielectric_Young_modulus_Pa: 7.3e10                 # Young's modulus (Pa)
  Dielectric_thickness: 1.5e-6          # Dielectric thickness (m)
  DISH_0_m: 75e-9                         # Reference dish depth (m)
  k_peel: 6.66e12                       # Peel force constant (N/m⁴/K)\

  # === Adhesion_energy to Critical Peeling Stress Model Parameters ===
  # σ = Effective_Contact_Area * ((Gc_Jpm2 * E_GPa) / (CRIT_aY2_UM * (1.0 - NU**2)))^(1/2)
  CRIT_aY2_UM: 1.90                    # Geometric/Compliance factor (µm)
  GC_SIO2_JPM2: 2.0                     # Sio2 Adhesion energy (J/m²)
  GC_CU_JPM2: 25.0                      # Cu Adhesion energy (J/m²)
  Effective_Contact_Area: 1.0           # Fraction of pad area effectively bearing normal load

  # === ESD Parameters ===
  TILT_X_MEAN_DEG: 0.000
  TILT_X_STD_DEG: 0.01
  TILT_Y_MEAN_DEG: 0.000
  TILT_Y_STD_DEG: 0.01

  # === Simulation Control ===
  simulation_times: 1                  # Number of simulation iterations
  approximate_set: 1                   # 1: enable overlay simulation approximation, 0: disable

  # === Miscellaneous Parameters ===
  plot_flag: True                      # Enable plotting of results
 

#### ==================================================================== ####
#### Modeling parameters for Die-to-Wafer (W2W) hybrid bonding simulation.
#### ==================================================================== ####
d2w_modeling:
  # === General Settings ===
  MODE: "D2W_Hybrid_Bonding_Modeling"   # Name of the modeling
  DEBUG: false                          # Enable debug mode
  OUTPUT_DIR: "output/"
  INPUT_DIR: "input/"          # Output directory for simulation results
  DESIGN: "HBM_footprint_A_dummy_row_2"                      # Design name  
  # === Per Wafer Parameters ===
  PITCH_r_um: 55                            # Row pad pitch (µm) (In checkerboard layout, this is sqrt(2)/2 times of the real pitch)
  PITCH_c_um: 35                            # Column pad pitch (µm) (In checkerboard layout, this is sqrt(2)/2 times of the real pitch)
  DIE_W_um: 10990                          # Die width (µm)
  DIE_L_um: 9185                          # Die length (µm)
  PAD_ARR_ROW: 165
  PAD_ARR_COL: 312
  PAD_BOT_R_um: 9                      # Bottom Cu pad radius (um)
  PAD_TOP_R_um: 9                      # Top Cu pad radius (um)
  VOID_SHAPE: "circle"                  # Shape of void: "circle" or "square"
  dice_width: 100                      # Dice width to separate dies (µm)
  pad_yield_flag: True                  # Enable pad yield map generation
  pad_yield_map_sub_factor: 1          # Subsampling factor for pad yield map (1: no subsampling, 10: rows/10 and cols/10)
  PAD_ARRANGE_PATTERN: "checkerboard"
  
  # === Die Warpage Peeling Stress Mdodel ===
  # === Bottom Wafer Settings ===
  B_Chip_Cu_V: 0.40                     # Efficient chip layer Cu volume density
  B_Chip_Sio2_V: 0.60                   # Efficient chip layer Sio2 volume density
  B_Chip_Si_V: 0.00                     # Efficient chip layer Si volume density
  B_Chip_T: 3.2e-6                      # Efficient chip layer thickness (m)
  B_Sub_Cu_V: 0.10                      # Efficient substrate layer Cu volume density
  B_Sub_Sio2_V: 0.00                    # Efficient substrate layer Sio2 volume density
  B_Sub_Si_V: 0.90                      # Efficient substrate layer si volume density
  B_Sub_T: 775e-6                       # Efficient substrate layer thickness (m)
  S_INIT_A_M: 100e-9                   # Pre-anneal warpages (m)
  # === Top Wafer Settings ===
  T_Chip_Cu_V: 0.30                     # Efficient chip layer Cu volume density
  T_Chip_Sio2_V: 0.70                   # Efficient chip layer Sio2 volume density
  T_Chip_Si_V: 0.00                     # Efficient chip layer Si volume density
  T_Chip_T: 3.2e-6                      # Efficient chip layer thickness (m)
  T_Sub_Cu_V: 0.10                      # Efficient substrate layer Cu volume density
  T_Sub_Sio2_V: 0.00                    # Efficient substrate layer Sio2 volume density
  T_Sub_Si_V: 0.90                      # Efficient substrate layer si volume density
  T_Sub_T: 775e-6                       # Efficient substrate layer thickness (m)
  S_INIT_B_M: 0.0e-6                    # Pre-anneal warpages (m)

 

  CONTACT_AREA_CONSTRAINT: 0.75         # Minimum allowed contact area ratio
  CRITICAL_DIST_CONSTRAINT: 0.75        # Minimum distance constraint for critical pads

  # === Overlay Parameters ===
  num_samples: 10000                    # Number of samples for misalignment input parameters
  RANDOM_MISALIGNMENT_MEAN_um: 0        # Mean of random overlay error (µm)
  RANDOM_MISALIGNMENT_STD_um: 2e-2         # Std of random overlay error (µm)
  SYSTEM_TRANSLATION_X_MEAN_um: 0       # Mean of systematic X translation (µm)
  SYSTEM_TRANSLATION_X_STD_um: 2e-2        # Std of systematic X translation (µm)
  SYSTEM_TRANSLATION_Y_MEAN_um: 0       # Mean of systematic Y translation (µm)
  SYSTEM_TRANSLATION_Y_STD_um: 2e-2        # Std of systematic Y translation (µm)
  SYSTEM_ROTATION_MEAN_rad: 2e-6            # Mean of systematic rotation (rad)
  SYSTEM_ROTATION_STD_rad: 5e-7             # Std of systematic rotation (rad)
  BOW_DIFFERENCE_MEAN_um: 0.5               # Bow difference mean (µm)
  BOW_DIFFERENCE_STD_um: 0.1                 # Bow difference std (µm)
  k_mag: 0.1                           # Magnification slope coefficient
  M_0: 0                                # Magnification offset

  # === Defect Parameters ===
  first_contact: 'horizontal-edge'            # First contact location: 'center' or 'vertical-edge' or 'horizontal-edge' or 'corner' (left-bottom)
  D0: 1e-9                              # Particle density (1/µm²)
  z: 3                                  # Thickness distribution exponent factor
  t_0: 0.1                              # Minimum particle thickness (µm)
  k_r: 1.8e-4
  k_r0: 230
  k_L: 6.2e-2
  k_n: 9e-5
  k_S: 2.7

  # === Cu Expansion / Dishing Parameters ===
  TOP_DISH_MEAN_nm: -1.0                  # Top pad height mean (nm)
  TOP_DISH_STD_nm: 0.6                     # Top pad height std (nm)
  BOT_DISH_MEAN_nm: -1.0                  # Bottom pad height mean (nm)
  BOT_DISH_STD_nm: 0.6                     # Bottom pad height std (nm)
  k_et: 0.053                           # Top Cu expansion coef (nm/K)
  k_eb: 0.053                           # Bottom Cu expansion coef (nm/K)
  T_R: 25                               # Room temperature (°C)
  T_anl: 300                            # Annealing temperature (°C)
  CU_E_GPA: 91.8                        # Cu Young’s modulus (GPa)
  CU_NU: 0.34                           # Cu Poisson’s ratio 
  CU_ALPHA_PPM: 17.6                    # Cu coefficient of thermal expansion (CTE) (ppm/°C)
  OX_E_GPA: 73.0                        # Sio2 Young’s modulus (GPa)
  OX_NU: 0.17                           # Sio2 Poisson’s ratio
  OX_ALPHA_PPM: 0.5                     # Sio2 coefficient of thermal expansion (CTE) (ppm/°C)
  SI_E_GPA: 131.0                        # Si Young’s modulus (GPa)
  SI_NU: 0.28                           # Si Poisson’s ratio
  SI_ALPHA_PPM: 2.6                     # Si coefficient of thermal expansion (CTE) (ppm/°C)

  # === Cu & Sio2 peeling stress model Parameters ===
  # === heat up and dwell stage ===
  # σ_m = σ_e + R_P * σ_p + R_C * σ_c
  # σ_e = {σ_t, SIGMA_Y_MPA}_min 
  # σ_p = {0, σ_t-SIGMA_Y_MPA}_max
  # σ_d = CREEP_FACTOR * σ_m
  SIGMA_Y_MPA: 321.0                    # Elastic yield point (MPa)
  R_P: 60.0                             # Weight of plastic part in the normal-approach driver
  R_C: 20.0                             # Weight of creep-equivalent part in the normal-approach driver
  CREEP_FACTOR: 0.01                    # Weight of creep-equivalent part for dwell stage
  
  # t_cu(T) = TCU_BASE_UM * exp(TCU_K_PER_C * (T - T_R))
  TCU_BASE_UM: 0.036                    # Base thickness for heat-stage Cu participation thickness (µm)
  TCU_K_PER_C: 0.0031                   # Exponential temperature rate (1/°C)
 
  # ϕ = PHI_CU0 + (1 - PHI_CU0)*((δ-2*Dishing)/2*Dishing)^ETA_GROWTH
  PHI_CU0: 0.000001                     # Baseline Cu–Cu contact fraction once the threshold is exceeded
  ETA_GROWTH: 0.122019                  # Power exponent in the (uncapped) contact growth law
  
  # k_n = M_cu/T_INT_NM
  T_INT_NM: 13000.0                     # Interface normal compliance thickness (nm)

  # === heat up and dwell stage ===
  # σy_cool = {SIGMA_Y_MPA, (1-COOL_BAUSINGER_REDUCTION) * SIGMA_Y_MPA + COOL_A_HARD_MPA * (1 - exp(-COOL_K_HARD_PER_MPA * {0,σ_p_heat}_max)) }_min
  COOL_BAUSINGER_REDUCTION: 0.70        # Cool-down effective yield reduction factor
  COOL_A_HARD_MPA: 80.0                 # Isotropic hardening Amplitude (MPa)
  COOL_K_HARD_PER_MPA: 0.032380         # Isotropic hardening rate (1/MPa)

  # kn_cool = k_n * KN_COOL_GAIN * (1- VISC_LAMBDA*(Acu/Acell)^VISC_EXP)
  KN_COOL_GAIN: 3.0                     # Gain of interface normal stiffness at cool-down
  VISC_LAMBDA: 0.836626                 # Coefficient of viscous attenuation applied to the Cu–Cu peel stress during cool-down
  VISC_EXP: 0.5                         # Sensitivity of stress reduction to fill fraction
  
  # ke_cool = TCU_CONST_UM_COOL* (1 + KDISH_TCU_GAIN_PER_NM * Dishing)
  TCU_CONST_UM_COOL: 0.122074           # Constant Cu participation thickness during the cool-down stage (µm)
  KDISH_TCU_GAIN_PER_NM: 0.010466       # Coefficient for the linear dishing gain applied to Cu participation thickness (1/nm)

  # === Roughness Parameters ===
  Asperity_R_m: 2e-6                      # Asperity curvature radius (m)
  Roughness_sigma_m: 0.5e-9               # Roughness standard deviation (m)
  eta_s: 40e12                          # Asperity density (1/m²)
  Roughness_constant: 0.07
  Adhesion_energy: 1.2                  # Adhesion energy (J/m²)
  Dielectric_Young_modulus_Pa: 73e9                   # Dielectric Young's modulus (Pa)
  Dielectric_thickness: 1.5e-6          # Dielectric layer thickness (m)
  DISH_0_m: 75e-9                         # Reference dish height (m)
  k_peel: 6.66e15                       # Peel force coefficient (N/m⁴/K)

  # === Adhesion_energy to Critical Peeling Stress Model Parameters ===
  # σ = Effective_Contact_Area * ((Gc_Jpm2 * E_GPa) / (CRIT_aY2_UM * (1.0 - NU**2)))^(1/2)
  CRIT_aY2_UM: 1.90                    # Geometric/Compliance factor (µm)
  GC_SIO2_JPM2: 2.0                     # Sio2 Adhesion energy (J/m²)
  GC_CU_JPM2: 25.0                      # Cu Adhesion energy (J/m²)
  Effective_Contact_Area: 1.0           # Fraction of pad area effectively bearing normal load

  # === ESD Parameters ===
  TILT_X_MEAN_DEG: 0.000
  TILT_X_STD_DEG: 0.01
  TILT_Y_MEAN_DEG: 0.000
  TILT_Y_STD_DEG: 0.01
  n_tilts_samples: 1                  # Number of tilt samples for ESD simulation
  n_dishes_samples: 1                # Number of dish samples for ESD simulation

  # === Miscellaneous Parameters ===
  plot_flag: True                      # Enable plotting of results
 